import type { GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import { sheet, SheetSchema } from "../src/util/gapi";

interface Props {
  sheets: SheetSchema[];
}

const Home: NextPage<Props> = ({ sheets }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 bg-stone-900 text-stone-50">
        {sheets.map((sheet) => (
          <div key={sheet.title}>
            <h2 className="text-2xl font-bold my-4 text-stone-300">
              {sheet.title}
            </h2>
            <table className="w-full max-w-screen-xl">
              <thead className="border-b">
                <tr>
                  <th></th>

                  {sheet.schema.map((shape) => (
                    <th
                      key={shape.name}
                      scope="col"
                      className="text-sm font-medium px-6 py-4 text-left capitalize"
                    >
                      {shape.name}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {sheet.data.map((data, i) => (
                  <tr key={i} className="even:bg-stone-800">
                    <td className="text-sm">
                      <label className="px-6 py-4">
                        <input type="checkbox" />
                      </label>
                    </td>
                    {Object.values(data).map((v, i) => (
                      <td key={i} className="text-sm font-light px-6 py-4">
                        {v}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ))}
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span></span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps(context: GetStaticPropsContext) {
  await sheet.init();

  return {
    props: {
      sheets: await sheet.getFormattedData(),
    },
  };
}

export default Home;
