#!/usr/bin/env python3
"""
Add Italian translations (title_it and data_it fields) to ashesofwar.yaml
"""
import re

TITLE_TRANSLATIONS = {
    'title: Ashes of War': 'title_it: Ceneri di Guerra',
    '    title: "Heavy"': '    title_it: "Pesante"',
    '    title: "Keen"': '    title_it: "Affilata"',
    '    title: "Quality"': '    title_it: "Qualità"',
    '    title: "Magic"': '    title_it: "Magica"',
    '    title: "Fire"': '    title_it: "Fuoco"',
    '    title: "Flame"': '    title_it: "Fiamma"',
    '    title: "Lightning"': '    title_it: "Fulmine"',
    '    title: "Sacred"': '    title_it: "Sacra"',
    '    title: "Poison"': '    title_it: "Veleno"',
    '    title: "Blood"': '    title_it: "Sangue"',
    '    title: "Cold"': '    title_it: "Gelo"',
    '    title: "Occult"': '    title_it: "Occulta"',
    '    title: "Standard"': '    title_it: "Standard"',
    '    title: "Misc."': '    title_it: "Varie"',
}

DATA_TRANSLATIONS = {
    # --- Heavy ---
    "5_11": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Stamp+(Upward+Cut)">Stamp (Upward Cut)</a>", "Impugna l\'arma e assumi una postura bassa che previene il rinculo dalla maggior parte degli attacchi nemici. Seguito da un attacco forte per un colpo verso l\'alto.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "5_10": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Stamp+(Sweep)">Stamp (Sweep)</a>", "Impugna l\'arma e assumi una postura bassa che previene il rinculo dalla maggior parte degli attacchi nemici. Seguito da un attacco forte per un colpo a spazzata.", "Lasciato cadere da uno scarabeo invisibile sulla spiaggia est delle Catacombe Piede della Tempesta, nell\'ovest di Limgrave."]',
    "5_14": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Wild+Strikes">Wild Strikes</a>", "Colpisci con l\'arma con foga sfrenata. Tieni premuto per continuare a colpire. Può essere seguito da un attacco normale o forte.", "Lasciato cadere da uno scarabeo sul sentiero a nord del sito di grazia Tunnel di Castleward, nel nordovest di Limgrave."]',
    "5_9":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Lion\'s+Claw">Lion\'s Claw</a>", "Abilità dei Criniere Rosse, che combatterono al fianco del Generale Radahn. Rotola in avanti, colpendo i nemici con l\'arma.", "Lasciato cadere dal Guardiano Leone a Fort Gael, nell\'est di Caelid."]',
    "5_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Cragblade">Cragblade</a>", "Potenzia l\'arma con la terra.", "Lasciato cadere da uno scarabeo a ovest del sito di grazia Impassable Greatbridge, nel sud di Caelid."]',
    "5_8":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Kick">Kick</a>", "Respingi un nemico con un calcio alto. Efficace contro i nemici in guardia e può rompere la postura del nemico. A volte uno strumento semplice è il più efficace.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "5_5":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Endure">Endure</a>", "Assumi una postura ancorata per resistere agli attacchi in arrivo, aumentando brevemente la poise. Il danno ricevuto durante questa abilità è ridotto.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "5_6":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Ground+Slam">Ground Slam</a>", "Salta in alto nell\'aria e abbattiti sul terreno davanti a te. Il violento impatto invia un\'onda d\'urto in tutte le direzioni.", "Lasciato cadere da uno scarabeo su una piccola collina, a sudovest del Piccolo Albero Eterno nel Bosco Nebbia, nell\'est di Limgrave."]',
    "5_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Earthshaker">Earthshaker</a>", "Conficca l\'arma nel terreno, poi raccoglie le forze per scatenare un\'onda d\'urto che scuote la terra. Seguito da un attacco forte per colpire in una spazzata.", "Lasciato cadere da uno scarabeo invisibile fermo, all\'incrocio stradale a sudovest del sito di grazia Altus Highway Junction nel sud dell\'Altopiano di Altus."]',
    "5_7":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Hoarah+Loux\'s+Earthshaker">Hoarah Loux\'s Earthshaker</a>", "Sbatte entrambe le mani sul terreno per scuoterlo violentemente e scatenare un\'onda d\'urto. Un ulteriore input permette di sbattere di nuovo sul terreno.", "Ottenuto in cambio della Remembrance di Hoarah Loux alla Tavola Rotonda."]',
    "5_13": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+War+Cry">War Cry</a>", "Lancia un grido di guerra per rinvigorire lo spirito e aumentare il potere d\'attacco. Mentre è attiva, gli attacchi forti si trasformano in attacchi carichi.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "5_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Barbaric+Roar">Barbaric Roar</a>", "Aumenta il potere d\'attacco. Gli attacchi forti si trasformano in combo selvagge.", "Lasciato cadere da uno scarabeo nel Villaggio Nascosto nella Gola, nel nord di Liurnia."]',
    "5_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Braggart\'s+Roar">Braggart\'s Roar</a>", "Proclama la tua presenza con un ruggito spaccone. Aumenta il potere d\'attacco, la difesa e la velocità di recupero della resistenza.", "Lasciato cadere da Blackguard Big Boggart, rimovibile dalla sua arma Palla di Ferro."]',
    "5_12": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Troll\'s+Roar">Troll\'s Roar</a>", "Genera una potente onda d\'urto poi abbatte l\'arma.", "Trovato sopra la grande roccia a sud del sito di grazia Chiesa del Riposo, nel sud delle Vette dei Giganti."]',
    "20_3": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Spinning+Gravity+Thrust">Spinning Gravity Thrust</a>", "Un\'abilità gravitazionale affinata dai discepoli di un Signore Alabastro. Usa il potere gravitazionale per sospendersi in aria prima di ruotare il corpo e caricare in avanti. Un ulteriore input permette un attacco di follow-up.", "In dotazione alla Sword Lance, uno dei possibili premi scambiando la Remembrance del Cinghiale Selvaggio con Enia alla Tavola Rotonda."]',
    "20_17": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Savage+Lion\'s+Claw">Savage Lion\'s Claw</a>", "Abilità dei particolarmente coraggiosi, anche tra i Criniere Rosse. Rotola in avanti, colpendo i nemici con l\'arma. Un colpo aggiuntivo può essere eseguito con un ulteriore input.", "Dal sito di grazia Three-Path Cross in Gravesite Plain, segui il muro sul lato sinistro e prosegui verso nord. Troverai un piccolo accampamento con la Cenere di Guerra."]',
    # --- Quality ---
    "11_7":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Square+Off">Square Off</a>", "Questa abilità inizia con la spada tenuta orizzontale. Segui con un attacco normale per tagliare verso l\'alto attraverso la guardia del nemico, o un attacco forte per eseguire una carica con stoccata.", "Lasciato cadere da uno scarabeo sulla scogliera ovest, a nord del sito di grazia Worshippers\' Woods nel Fiume Siofra."]',
    "11_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Charge+Forth">Charge Forth</a>", "Carica rapidamente in avanti con l\'arma all\'anca, portando lo slancio in una stoccata. Tieni premuto per coprire una distanza maggiore.", "Lasciato cadere da uno scarabeo attaccato alla faccia inferiore del ponte a nord del sito di grazia Fallen Ruins of the Lakes, nella zona centrale di Liurnia. Sarà necessario mirare manualmente."]',
    "11_6":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Spinning+Strikes">Spinning Strikes</a>", "Abilità per armi ad asta che esegue attacchi rotanti continui. Tieni premuto per continuare l\'attacco. Può essere seguito da un attacco normale o forte. Annulla proiettili come frecce durante la rotazione.", "Lasciato cadere da Edgar alla Revenger\'s Shack, rimovibile dalla sua arma Banished Knight\'s Halberd +8."]',
    "11_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Giant+Hunt">Giant Hunt</a>", "Abilità sviluppata per affrontare nemici giganteschi. Avanza da una postura bassa, portando lo slancio in un\'improvvisa stoccata ascendente.", "Lasciato cadere dalla Cavalleria Notturna sulla strada a sud del sito di grazia Bellum Church, nel nord di Liurnia."]',
    "11_9":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Storm+Blade">Storm Blade</a>", "L\'arma viene avvolta in una lama tempestosa che può essere lanciata in rapida successione.", "Lasciato cadere dal Custode della Tomba nelle Catacombe Murkwater in Limgrave, venduto anche da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "11_8":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Storm+Assault">Storm Assault</a>", "Una delle abilità che incanalano le tempeste di Stormveil. Balza in avanti attraverso i venti di tempesta circostanti e conficca l\'arma verso il basso. L\'attacco produrrà ulteriori venti di tempesta al punto di impatto.", "Lasciato cadere da uno scarabeo sotto Stormveil Castle, appena prima di scendere verso il boss Ulcerated Tree Spirit."]',
    "11_11": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Stormcaller">Stormcaller</a>", "Una delle abilità che incanalano le tempeste di Stormveil. Fai ruotare l\'arma per creare venti di tempesta circostanti. Input ripetuti consentono fino a due attacchi di follow-up.", "Lasciato cadere da uno scarabeo sul sentiero di fronte al sito di grazia Secluded Cell in Stormveil Castle, Limgrave."]',
    "11_10": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Storm+Stomp">Storm Stomp</a>", "Una delle abilità che incanalano le tempeste di Stormveil. Calpesta forte il terreno per sollevare una tempesta momentanea.", "Trovato in un forziere nella piccola stanza sotterranea delle Gatefront Ruins, a sudest del sito di grazia Gatefront Ruins."]',
    "11_12": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Vacuum+Slice">Vacuum Slice</a>", "Abilità perduta degli antichi eroi. Tieni l\'arma in alto per circondarla con un vuoto lacerante, poi lanciala in avanti come un proiettile a lama.", "Trovato all\'interno del tempio in rovina sul terreno sotto le cascate vicino al sito di grazia Across the Roots, nelle Deeproot Depths."]',
    "11_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Phantom+Slash">Phantom Slash</a>", "Abilità ispirata ai cari ricordi della Cavalleria Notturna. Crea un\'apparizione dell\'ex istruttore dei cavalieri che guida un\'oscillazione ascendente congiunta in avanzamento. Un input aggiuntivo permette un attacco di follow-up.", "Lasciato cadere dalla Cavalleria Notturna sul sentiero a nordest del sito di grazia Forbidden Lands, nelle Vette dei Giganti."]',
    "11_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Determination">Determination</a>", "Tieni il piatto dell\'arma sul viso e giura la tua risolutezza, potenziando il tuo prossimo attacco.", "Lasciato cadere da uno scarabeo sulla strada a sudest del sito di grazia Agheel Lake North, in Limgrave."]',
    "11_5":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Royal+Knight\'s+Resolve">Royal Knight\'s Resolve</a>", "Abilità dei cavalieri che servivano un tempo il Signore degli Eletti. Tieni il piatto dell\'arma sul viso e giura la tua risolutezza, potenziando enormemente il tuo prossimo attacco.", "Trovato in fondo alla stanza con le gabbie dietro la statua dell\'imp nel Volcano Manor. Dopo aver attraversato il Manor verso il portale del boss, troverai la statua dell\'imp nelle vicinanze."]',
    "20_14": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Wing+Stance">Wing Stance</a>", "Assumi con calma una postura sul lato destro. L\'attacco normale attiva una rapida combinazione di tre tagli. L\'attacco forte attiva una stoccata con balzo.", "Castle Ensis: All\'interno di un forziere nella torre raggiungibile saltando oltre il bordo appena fuori dal sito di grazia Castle Lord\'s Chamber e seguendo la scogliera verso il basso fino alla torre, poi salendo due scale a pioli."]',
    # --- Magic ---
    "8_5":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Glintstone+Pebble">Glintstone Pebble</a>", "Abilità che impiega la stregoneria della pietra lucente omonima. Segui con un attacco forte per concatenare questa abilità in una stoccata in avanzamento, eseguita mentre l\'arma è ancora impregnata di pietra lucente.", "Venduto da Rogier in Stormveil Castle o alla Tavola Rotonda."]',
    "8_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Glintblade+Phalanx">Glintblade Phalanx</a>", "Abilità che crea lame di pietra lucente sopra la testa e attacca i nemici automaticamente quando si avvicinano abbastanza.", "Donato da Rogier dopo aver sconfitto Godrick, parlagli alla Tavola Rotonda. Rimovibile dalla sua arma Rogier\'s Rapier."]',
    "8_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Carian+Greatsword">Carian Greatsword</a>", "Il prestigio reale di Caria incarnato in un\'abilità. Trasforma la lama in una grande spada magica e abbattila. Può essere caricata per aumentarne la potenza.", "Venduto da Rogier in Stormveil Castle o alla Tavola Rotonda."]',
    "8_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Carian+Grandeur">Carian Grandeur</a>", "Il prestigio reale di Caria incarnato in un\'abilità. Trasforma la lama in una grande spada magica e abbattila. Può essere caricata fino a due livelli per aumentarne la potenza.", "Trovato su un cadavere in cima a un arco nella Caria Manor, in Liurnia. Accessibile salendo le scale oltre il gigante e girando a sinistra, attraverso la porta scendi fino al secondo bordo di scogliera con un grande vaso."]',
    "8_8":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Spinning+Weapon">Spinning Weapon</a>", "Abilità difensiva delle principesse di Caria. Solleva l\'arma in mezz\'aria, poi la fa ruotare violentemente. Chi viene toccato subirà attacchi successivi.", "Venduto da Rogier in Stormveil Castle o alla Tavola Rotonda."]',
    "8_7":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Loretta\'s+Slash">Loretta\'s Slash</a>", "Abilità di Loretta, la Cavaliere Reale. Balza in avanti, impregnando la lama di pietra lucente, poi scendi accelerando in un taglio a spazzata.", "Lasciato cadere dalla Cavaliere Reale Loretta nella Caria Manor, Liurnia."]',
    "8_10": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Waves+of+Darkness">Waves of Darkness</a>", "Conficca l\'arma nel terreno per rilasciare tre onde di oscurità.", "Ottenuto in cambio della Remembrance del Naturalnato alla Tavola Rotonda."]',
    "8_6":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Gravitas">Gravitas</a>", "Perfora il terreno con l\'arma per danneggiare i nemici mentre un\'ondata di gravità li attira.", "Lasciato cadere da un Viandante Esile sulla spiaggia a ovest del sito di grazia Seaside Ruins, nel sud di Limgrave. Fare attenzione a scendere dalle scogliere."]',
    "20_20": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Carian+Sovereignty">Carian Sovereignty</a>", "Abilità tramandata nella famiglia reale di Caria. Trasforma la lama in una grande spada magica e abbattila. Un input aggiuntivo segue con un colpo orizzontale. Carica uno dei due attacchi per aumentarne la potenza.", "Acquisita da uno scarabeo lacrima all\'interno di una caverna a sudovest della Cathedral of Manus Metyr, piena di lucciole di pietra lucente. Lo scarabeo si trova sul soffitto della caverna."]',
    # --- Fire ---
    "3_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Flaming+Strike">Flaming Strike</a>", "Abilità che emette fiamme in un ampio arco frontale. Segui con un attacco forte per eseguire una stoccata con avanzamento e spazzata. Questo rivestirà anche l\'arma di fuoco.", "Lasciato cadere da uno scarabeo fuori dal muro sud del Redmane Castle in Caelid."]',
    "3_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Flame+of+the+Redmanes">Flame of the Redmanes</a>", "Abilità dei Criniere Rosse, che combatterono al fianco del Generale Radahn. Produce una potente esplosione di fiamme in un ampio arco frontale.", "Lasciato cadere da uno scarabeo invisibile vicino al sito di grazia Fort Gael North, nell\'ovest di Caelid."]',
    "3_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Eruption">Eruption</a>", "Conficcando l\'arma nel terreno si genererà lava ribollente che fuoriesce anche al rilascio.", "Venduto da Bernahl nel Volcano Manor."]',
    # --- Flame ---
    "4_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Prelate\'s+Charge">Prelate\'s Charge</a>", "Sbatte l\'arma nel terreno per creare un\'ondata di fiamme, poi carica. Tieni premuto per continuare la carica.", "Lasciato cadere da uno scarabeo appeso a un albero nell\'accampamento, a sud del sito di grazia Whiteridge Road, nelle Vette dei Giganti."]',
    "4_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Black+Flame+Tornado">Black Flame Tornado</a>", "Fai roteare l\'arma sopra la testa e poi conficcarla nel terreno per evocare un vortice infuriante di fiamme nere. Tieni premuto per creare un tornado di fiamma iniziale mentre si fa roteare l\'arma.", "Lasciato cadere dal Duo Godskin nel Crumbling Farum Azula."]',
    "20_16": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Flame+Skewer">Flame Skewer</a>", "Abilità di Queelign dei Cavalieri del Fuoco. Avvolgi l\'arma nelle fiamme e assumi una postura bassa prima di infilzare il nemico in un unico movimento. L\'attacco forte scatena un attacco di follow-up infuocato.", "Acquisita come ricompensa sconfiggendo l\'invasore NPC Fire Knight Queelign una seconda volta."]',
    "20_19": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Flame+Spear">Flame Spear</a>", "Abilità di Kood, capitano dei Cavalieri del Fuoco. Prepara l\'arma per un attacco con stoccata e scatena una lancia di fiamme dritta davanti a sé. Carica l\'attacco per aumentare i danni e la distanza percorsa.", "Shadow Keep, Sesto Piano: Arrampicati sulle statue dopo aver usato la leva per spostarle. Esci, gira a destra e sali le scale, gira a sinistra per trovare un Cavaliere del Fuoco alla fine del ponte."]',
    # --- Lightning ---
    "7_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Thunderbolt">Thunderbolt</a>", "Alza l\'arma in alto per far scendere un fulmine. Può essere sparato in rapida successione.", "Lasciato cadere da uno scarabeo da qualche parte in Leyndell, Capitale Reale. Partendo dal sito di grazia Avenue Balcony, scendi le scale e attraversa la porta davanti. Gira immediatamente a sinistra e segui il parapetto finché non vedi lo scarabeo dall\'altro lato sotto."]',
    "7_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Lightning+Slash">Lightning Slash</a>", "Fa scendere un fulmine nell\'arma, poi abbattila per creare un\'esplosiva scarica. L\'arma mantiene l\'incantesimo del fulmine per un po\'.", "Lasciato cadere da uno scarabeo nel piccolo accampamento fuori dalle mura, a nordovest del sito di grazia Hermit Merchant\'s Shack, nell\'Altopiano di Altus."]',
    "7_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Lightning+Ram">Lightning Ram</a>", "Abilità ispirata agli arieti che ruzzolano. Emetti un belato, poi rotola in avanti avvolto nel fulmine. I rotolamenti possono essere ripetuti in rapida successione.", "Lasciato cadere da uno scarabeo a est della Stormcaller Church e a sudest della Sainted Hero\'s Grave, nell\'Altopiano di Altus."]',
    "20_15": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Blinkbolt">Blinkbolt</a>", "Abilità usata dai cavalieri dorati al servizio di Godwyn. Da una postura bassa, il corpo si trasforma in un fulmine e carica dritto avanti a velocità folgorante.", "Trovato in un forziere nelle Fog Rift Catacombs. Nella stanza della terza trappola a punte con un mago che spara dalla parte posteriore, attira la trappola verso il basso per saltare in un incavo. Sali fino a una stanza con un forziere."]',
    # --- Sacred ---
    "12_7":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Sacred+Blade">Sacred Blade</a>", "Conferisce agli attacchi dell\'arma essenza sacra e spara un proiettile a lama dorata. L\'arma mantiene la sua essenza sacra per un po\'.", "Lasciato cadere da uno scarabeo a nord del sito di grazia Third Church of Marika in Limgrave. Trovato vicino al balzo dello Spirito."]',
    "12_6":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Prayerful+Strike">Prayerful Strike</a>", "Alza l\'arma in preghiera, poi abbattila sul terreno. Questo colpo ispirato ripristina HP a sé e agli alleati vicini se va a segno.", "Lasciato cadere da uno scarabeo invisibile nella sezione ovest del fossato del Capital Outskirts. C\'è un arco pieno di lumache in mezzo alle due vasche, lo scarabeo corre avanti e indietro."]',
    "12_9":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Sacred+Ring+of+Light">Sacred Ring of Light</a>", "L\'arma raccoglie un anello sacro di luce e lo spara in avanti, l\'abilità può essere sparata in rapida successione.", "Lasciato cadere da uno scarabeo sul bordo orientale della Aeonian Swamp in Caelid. A est del sito di grazia Heart of Aeonia."]',
    "12_8":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Sacred+Order">Sacred Order</a>", "Abilità dei cavalieri fondamentalisti dell\'Ordine Dorato. Esegui un saluto e conferisci all\'arma essenza sacra.", "Lasciato cadere da uno scarabeo a nordovest del sito di grazia Abandoned Coffin nel sud dell\'Altopiano di Altus. Sul sentiero a ovest dell\'acqua."]',
    "12_10": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Shared+Order">Shared Order</a>", "Abilità dei cavalieri fondamentalisti dell\'Ordine Dorato. Conferisce all\'arma e a quelle degli alleati vicini essenza sacra.", "Lasciato cadere dalla Cavalleria Notturna sulla strada a sudovest del sito di grazia Altus Highway Junction, nell\'Altopiano di Altus."]',
    "12_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Golden+Land">Golden Land</a>", "Conficca l\'arma nel terreno, poi raccoglie le forze per scatenare un\'esplosione di energia sacra che si coagula in dardi dorati. Segui con un attacco forte per colpire in una spazzata.", "Lasciato cadere da uno scarabeo a sud del sito di grazia Great Waterfall Crest nelle Deeproot Depths. Dietro l\'Avatar dell\'Albero Eterno."]',
    "12_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Golden+Slam">Golden Slam</a>", "Salta e abbattiti sul terreno.", "Lasciato cadere da uno scarabeo a nordest del Piccolo Albero Eterno, nella sezione nordovest delle Woodfolk Ruins nell\'Altopiano di Altus."]',
    "12_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Golden+Vow">Golden Vow</a>", "Abilità tramandata dall\'antichità tra i cavalieri della capitale. Alza l\'arma in alto e giura di onorare l\'Albero Eterno in battaglia, conferendo a sé e agli alleati vicini aumento del potere d\'attacco e della difesa.", "Lasciato cadere da un Cavaliere di Godrick a cavallo sulla scogliera sopra le Deathtouched Catacombs a Stormhill, Limgrave."]',
    "12_11": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Vow+of+the+Indomitable">Vow of the Indomitable</a>", "Abilità degli antichi guerrieri dell\'Albero Eterno. Alza lo scudo in alto per imbuirti di potere dorato, concedendo momentanea invincibilità.", "Lasciato cadere da uno scarabeo nella zona della palude velenosa nel sud del lago di Liurnia. A sud del sito di grazia Folly on the Lake."]',
    "12_5":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Holy+Ground">Holy Ground</a>", "Alza lo scudo per creare un\'area consacrata dall\'Albero Eterno che ripristina continuamente HP e aumenta la difesa per sé e gli alleati al suo interno.", "Trovato quando i carri vengono distrutti nell\'Auriza Hero\'s Grave nel Capital Outskirts."]',
    "20_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Aspects+of+the+Crucible:+Wings">Aspects of the Crucible: Wings</a>", "Questa abilità ha origine dalle forme di vita del Crogiolo. Fai crescere un paio di ali dorate e prendere il volo prima di tuffarti sul nemico con l\'arma puntata. Un attacco rotante viene eseguito quando si impugna un\'arma gemella.", "Fort of Reprimand: il Cavaliere Nero Edredd lascia questa Cenere di Guerra alla sconfitta."]',
    # --- Poison ---
    "10_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Poisonous+Mist">Poisonous Mist</a>", "Ricopre l\'arma selezionata di veleno; il taglio diffonde la nebbia tossica in avanti. L\'arma mantiene il veleno per un po\'.", "Lasciato cadere da uno scarabeo nel sud della Swamp of Aeonia, a sudest del sito di grazia Aeonia Swamp Shore, in Caelid."]',
    "10_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Poison+Moth+Flight">Poison Moth Flight</a>", "Taglia con una lama intrisa di veleno. Se il colpo di follow-up colpisce un nemico avvelenato, causerà danni significativi.", "Lasciato cadere dalla Cavalleria Notturna sulla strada tra i siti di grazia Caelid Highway South e Southern Aeonia Swamp Bank, in Caelid."]',
    "20_23": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+The+Poison+Flower+Blooms+Twice">The Poison Flower Blooms Twice</a>", "Evoca pungiglioni di marciume scarlatto dal basso per pugnalare il nemico. Colpire con un attacco di follow-up un nemico già afflitto da veleno o marciume infligge danni massivi in un solo colpo.", "Lasciato cadere da uno Scarabeo Lacrima. Dal sito di grazia Ravine North nella Rauh Base, dirigiti a sud per attraversare il fiume e trovarlo vicino a una piccola pozza di marciume vicino ad alcune rovine."]',
    # --- Blood ---
    "1_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Blood+Blade">Blood Blade</a>", "Ferisciti per ricoprire l\'arma di sangue, poi scatena una lama di sangue aerea che provoca emorragia. Può essere sparata in rapida successione.", "Lasciato cadere da uno scarabeo in volo sopra l\'acqua, a nordest del sito di grazia Erdtree-Gazing Hill nell\'Altopiano di Altus."]',
    "1_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Bloody+Slash">Bloody Slash</a>", "Abilità del Giuramento del Sangue concessa dal Signore del Sangue. Da una postura bassa, ricopri la lama con il tuo stesso sangue per scatenare un taglio di sangue lacerant in un ampio arco.", "Lasciato cadere dal cavaliere in cima a Fort Haight."]',
    "1_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Blood+Tax">Blood Tax</a>", "Abilità del Giuramento del Sangue concessa dal Signore del Sangue. Ruota per accumulare potenza, poi scatena una raffica di stoccate che priva il bersaglio sia del sangue che degli HP.", "Lasciato cadere da uno scarabeo in una piccola grotta sul lato est del Palazzo Mohgwyn."]',
    "1_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Seppuku">Seppuku</a>", "Conficca la lama nel tuo stomaco per macchiarla di sangue. Aumenta il potere d\'attacco e migliora la capacità di infliggere perdita di sangue.", "Lasciato cadere da uno scarabeo invisibile a est del sito di grazia Freezing Lake nelle Vette dei Giganti."]',
    # --- Cold ---
    "2_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Ice+Spear">Ice Spear</a>", "Abilità dei guerrieri al servizio della Principessa Lunare Ranni. Fai ruotare l\'arma per rilasciare magia del freddo, poi canalizzala in una lancia di ghiaccio perforante.", "Lasciato cadere dalla Cavalleria Notturna a sudest del sito di grazia Gate Town Bridge, nell\'est di Liurnia."]',
    "2_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Chilling+Mist">Chilling Mist</a>", "Ricopri l\'arma di gelo, poi taglia diffondendo nebbia gelida in avanti. L\'arma mantiene il suo gelo per un po\'.", "Lasciato cadere da uno scarabeo nelle rovine a sud di Renna\'s Rise."]',
    "2_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Hoarfrost+Stomp">Hoarfrost Stomp</a>", "Calpesta forte per diffondere una scia di nebbia gelante sul terreno. La nebbia applica l\'effetto di stato gelo.", "Lasciato cadere da uno scarabeo invisibile nell\'acqua a sudest della Caria Manor."]',
    "20_18": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Divine+Beast+Frost+Stomp">Divine Beast Frost Stomp</a>", "Un\'abilità che imita la furia della danza della bestia divina. Alza una gamba in alto e abbattila con grande forza. Invia una potente ondata di gelo lungo il terreno. Può essere caricata per aumentare potenza e portata.", "Ottenuta scambiando la Remembrance del Leone Danzante con Enia alla Tavola Rotonda."]',
    "20_22": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Ghostflame+Call">Ghostflame Call</a>", "Protendi l\'arma per evocare fiamma fantasma. Segui con un attacco normale per incendiare il terreno con fiamma fantasma, o un attacco forte per scatenare una massiccia esplosione.", "Charo\'s Hidden Grave: Lasciato cadere dall\'Uccello del Rito della Morte."]',
    # --- Occult ---
    "9_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Spectral+Lance">Spectral Lance</a>", "Abilità dei Cavalieri Mausoleo senza testa. Lancia una lancia fantasmagorica sui nemici.", "Lasciato cadere da uno scarabeo nella Raya Lucaria Academy. Dal sito di grazia Church of the Cuckoo, procedi fino ai muri di pietra sorvegliati da molti cani. Dalla porta del muro, dirigiti a nord lungo un pendio tra lapidi e un albero; in fondo ci sarà lo scarabeo."]',
    "9_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Lifesteal+Fist">Lifesteal Fist</a>", "Abilità che dimostra la padronanza dell\'arte di controllare le energie vitali.", "Lasciato cadere da uno scarabeo sulla strada appena a ovest del sito di grazia Astray from Caelid Highway North in Caelid."]',
    "9_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+White+Shadow\'s+Lure">White Shadow\'s Lure</a>", "Tieni l\'arma in una breve preghiera silenziosa per creare un\'ombra bianca. L\'apparizione attira i nemici di corporatura umana che non sono in combattimento, attirando la loro aggressività.", "Lasciato cadere da uno scarabeo invisibile vicino al fiume a nordest del sito di grazia Inner Consecrated Snowfield, nel Campo Innevato Consacrato. Lo scarabeo viene inseguito da un gruppo di lupi."]',
    "9_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Assassin\'s+Gambit">Assassin\'s Gambit</a>", "Un\'abilità che maschera la presenza del giocatore al costo di una ferita autoinflitta. L\'abilità concede quasi-invisibilità e passi silenziosi.", "Venduto da Bernahl al Volcano Manor."]',
    "20_21": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Shriek+of+Sorrow">Shriek of Sorrow</a>", "Abilità utilizzata dai diseredati. Urla, facendo vacillare i nemici vicini, e al contempo richiama rancore profondo, aumentando il potere d\'attacco in base agli HP rimasti. Più bassi sono gli HP, maggiore è l\'effetto.", "Si trova nel Belurat Tower Settlement, nella piazza principale dove il Cavaliere del Fuoco Queelign ti invade, dietro il grande albero al centro."]',
    # --- Standard ---
    "13_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Mighty+Shot">Mighty Shot</a>", "Abilità di tiro con l\'arco eseguita da una postura obliqua. Prepara l\'arco, poi tira la corda fino al limite per aumentare la potenza del colpo, penetrando la guardia del nemico.", "Lasciato cadere da uno scarabeo sulla strada vicino all\'incrocio, a nord del sito di grazia Castle Morne Rampart nella Weeping Peninsula."]',
    "13_12": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Through+and+Through">Through and Through</a>", "Potente abilità di tiro con l\'arco usando un grande arco in postura obliqua. Prepara il grande arco, poi torci la corda per sparare un potente dardo che può perforare i nemici.", "Lasciato cadere da uno scarabeo invisibile a nordovest del sito di grazia Road of Iniquity nel Mt. Gelmir, anche a nordovest dell\'ingresso del Volcano Manor."]',
    "13_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Barrage">Barrage</a>", "Abilità di tiro con l\'arco usando un arco tenuto orizzontalmente. Prepara l\'arco, poi spara una rapida successione di frecce più veloci dell\'occhio.", "Lasciato cadere da uno scarabeo appena a nord del sito di grazia Seethewater River nell\'est del Mt. Gelmir."]',
    "13_10": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Sky+Shot">Sky Shot</a>", "Abilità di tiro con l\'arco eseguita da una postura bassa. Prepara l\'arco, poi spara una freccia in alto nell\'aria che si arcua per colpire il nemico dall\'alto quando scende.", "Lasciato cadere da uno scarabeo lungo le scogliere a nordovest del sito di grazia Isolated Merchant\'s Shack nel Dragonbarrow occidentale."]',
    "13_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Enchanted+Shot">Enchanted Shot</a>", "Un\'abilità in cui un\'essenza spirituale viene raccolta all\'interno della freccia, permettendole di volare più velocemente di una freccia normale. Cambia anche traiettoria per seguire il bersaglio.", "Lasciato cadere da uno scarabeo dietro una roccia vicino a un braciere, attraverso il prato a nord del sito di grazia Ancestral Woods in Nokron, Città Eterna."]',
    "13_7":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Rain+of+Arrows">Rain of Arrows</a>", "Abilità di tiro con l\'arco eseguita da una postura bassa. Prepara l\'arco, poi spara una raffica di frecce in cielo per fare piovere proiettili sul nemico.", "Ricompensa risolvendo il dipinto \'Redmane\' trovato in Sellia, Città della Stregoneria. Dopo aver guardato il dipinto, si trova sulle scogliere a est del Piccolo Albero Eterno nell\'est del Dragonbarrow."]',
    "13_6":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Parry">Parry</a>", "Usa questa abilità in sincronia con un attacco in mischia del nemico per deviarlo e rompere la sua postura. Questo fornisce un\'apertura per eseguire un colpo critico.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "12_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Golden+Parry">Golden Parry</a>", "Esegui un\'incantazione dell\'Albero Eterno e oscilla lo scudo per deviare gli attacchi nemici e rompere la loro postura. Efficace anche a una certa distanza.", "Lasciato cadere da uno scarabeo che scompare sul lato sinistro delle scale a sud del sito di grazia Outer Wall Battleground nel Capital Outskirts, Altus Plateau. Fare attenzione nell\'avvicinarsi poiché scomparirà immediatamente; si consiglia di cadergli sopra dall\'alto o colpirlo a distanza."]',
    "13_11": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Storm+Wall">Storm Wall</a>", "Oscilla lo scudo per creare un muro di venti di tempesta davanti a sé, deviando frecce e altri proiettili fisici. Può essere usata anche come una normale parata.", "Lasciato cadere da uno scarabeo nella piccola area dopo essere scesi dal ponte che aggira Stormveil Castle. Segui il percorso a nord dal sito di grazia Stormhill Shack senza girare a sinistra verso il castello."]',
    "13_8":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Shield+Bash">Shield Bash</a>", "Riparati dietro lo scudo prima di usare il peso corporeo per speronare i nemici mantenendo la postura di guardia. I nemici più deboli verranno respinti e possono persino essere storditi.", "Lasciato cadere da uno scarabeo teletrasportante appena a nordest del sito di grazia East Gate Bridge Trestle."]',
    "13_9":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Shield+Crash">Shield Crash</a>", "Impugna lo scudo con entrambe le mani e carica in avanti mantenendo la guardia. I nemici più deboli verranno respinti e possono persino essere storditi. Tieni premuto per estendere la carica.", "Lasciato cadere da uno scarabeo che scompare nelle Lux Ruins, sulla scogliera sopra il sito di grazia Erdtree-Gazing Hill nell\'est dell\'Altopiano di Altus."]',
    "13_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Barricade+Shield">Barricade Shield</a>", "Concentra la tua energia nello scudo, indurendolo temporaneamente per deviare colpi più potenti.", "Lasciato cadere dalla Cavalleria Notturna sulla strada a ovest del sito di grazia Castle Morne Rampart nella Weeping Peninsula."]',
    "8_9":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Thops\'s+Barrier">Thops\'s Barrier</a>", "Erigi un campo di forza magico mentre oscilli lo scudo per deviare stregonerie e incantazioni. Può essere usata anche come una normale parata.", "Lasciato cadere da uno scarabeo nella Church of Irith, appare solo dopo che Thops se n\'è andato per l\'accademia."]',
    "8_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Carian+Retaliation">Carian Retaliation</a>", "Oscilla lo scudo per dissipare le stregonerie e le incantazioni in arrivo, trasformando la magia in lame di pietra lucente di ritorsione. Può essere usata anche come una normale parata.", "Venduto da Pidia nella Caria Manor, in Liurnia. Pidia si trova scendendo una serie di scogliere sul lato sudest delle Tre Sorelle."]',
    "13_5":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+No+Skill">No Skill</a>", "Questa arma non ha abilità. Se l\'arma nell\'altra mano ha un\'abilità, verrà usata quella.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "20_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Dryleaf+Whirlwind">Dryleaf Whirlwind</a>", "Questa abilità rappresenta il culmine dell\'arte marziale di Dane basata sul gioco di gambe. Alzati in aria con una serie di calci rotanti prima di abbattersi con un colpo finale. Imbuisce gli attacchi con i piedi di energia, aumentandone la portata.", "Dal sito di grazia Rauh Ancient Ruins, East, procedi verso nordest e troverai la Cenere su un bordo, accanto a una colonna e vicino a una cascata."]',
    "20_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Palm+Blast">Palm Blast</a>", "Abilità dei cercatori spirituali noti come la Setta Fogliaasciutta. Imbui la mano di energia prima di usare un colpo di palmo per scatenare un\'esplosione. La già notevole potenza e l\'impatto possono essere potenziati caricando l\'attacco.", "Al sito di grazia Moorth Ruins, usa l\'emote \'May The Best Win\' davanti al Monaco Dryleaf Dane; inizierà una battaglia e vincendo si otterrà l\'arma e la sua Cenere di Guerra."]',
    "20_7":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Wall+of+Sparks">Wall of Sparks</a>", "Sparge polvere profumata nelle vicinanze, producendo intense scintille dopo un breve ritardo. Può essere caricata per aumentare potenza e portata. Le proprietà delle scintille sono determinate dalla bottiglia di profumo usata.", "Shadow Keep: Prendi il montacarichi a sinistra scendendo dal sito di grazia Storehouse, first-floor. Prendi la prima uscita a destra, poi la prima a sinistra. Troverai questo oggetto su un cadavere seduto sui binari."]',
    "20_8":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Rolling+Sparks">Rolling Sparks</a>", "Sparge polvere profumata davanti a sé, scatenando esplosioni di scintille letali. Le proprietà delle scintille sono determinate dalla bottiglia di profumo usata.", "Può essere saccheggiato da uno scarabeo volante sul lato orientale del grande accampamento a sud di Shadow Keep. Sali la collina oltre alcuni profumieri e lo troverai in cima nell\'aria."]',
    "20_24": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Igon\'s+Drake+Hunt">Igon\'s Drake Hunt</a>", "Abilità di Igon, guerriero dei draghi. Prepara l\'arco prima di scatenare un tiro contorto con un gran ruggito che ne aumenta considerevolmente la potenza.", "Si trova evocando Igon e poi sconfiggendo Bayle il Terribile; questo causerà la morte di Igon nella sua posizione precedente, appena a sudest del Foot of the Jagged Peak; il suo corpo avrà sia l\'Igon\'s Greatbow che il suo set."]',
    "20_25": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Shield+Strike">Shield Strike</a>", "Un\'abilità che usa lo scudo per attaccare. Input ripetuti consentono fino a tre attacchi di follow-up.", "Trovato pre-equipaggiato sullo Dueling Shield saccheggiato da un cadavere in Shadow Keep."]',
    # --- Misc ---
    "14_1":  '        data_it: ["Lost Ashes of War", "Ceneri di guerra prive di qualsiasi ricordo di battaglia. Non è possibile applicare alcun tipo di affinità nel loro stato attuale, ma possono essere usate da Hewg, Maestro Fabbro della Tavola Rotonda, per ricreare altre ceneri."]',
    # --- Keen ---
    "6_9":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Spinning+Slash">Spinning Slash</a>", "Abilità preferita dai guerrieri abili. Colpisci i nemici mentre il corpo ruota. Un input aggiuntivo permette un attacco di follow-up.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "6_4":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Impaling+Thrust">Impaling Thrust</a>", "Abilità che consente alle armi perforanti di superare gli scudi nemici. Accumula potenza, poi lancia in avanti una poderosa stoccata che perfora la guardia del nemico.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "6_5":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Piercing+Fang">Piercing Fang</a>", "Abilità usata da Yura, il Cacciatore di Dita Insanguinate. Partendo con la lama tenuta orizzontalmente, esegui una poderosa stoccata che non può essere bloccata.", "Lasciato cadere da Yura alla morte o durante la sua missione, rimovibile dalla sua arma Nagakiba."]',
    "6_8":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Repeating+Thrust">Repeating Thrust</a>", "Ruota per accumulare potenza, poi scatena una raffica di stoccate. Questa abilità richiede un po\' di tempo per caricarsi, ma è molto potente.", "Lasciato cadere dalla Cavalleria Notturna sulla strada a sudest di Agheel Lake North, in Limgrave."]',
    "6_3":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Double+Slash">Double Slash</a>", "Abilità dei spadaccini superiori. Esegui un attacco a taglio incrociato da una postura bassa. Input ripetuti consentono fino a due attacchi di follow-up.", "Lasciato cadere da uno scarabeo sui tetti est di Sellia, appena a sudovest del sito di grazia Sellia Under-stair, in Caelid."]',
    "6_10": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Sword+Dance">Sword Dance</a>", "Avvicinati rapidamente per eseguire una serie di tagli ascendenti rotanti. Segui con un input aggiuntivo per concludere con un taglio discendente.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "6_11": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Unsheathe">Unsheathe</a>", "Abilità degli spadaccini della Terra delle Canne. Rinfodera la lama, tenendola all\'anca in una postura composta. Segui con un attacco normale o forte per eseguire un veloce attacco a taglio.", "Lasciato cadere da uno scarabeo sul bordo del Lago Agheel vicino ai granchi giganti, a nordovest del sito di grazia Agheel Lake South, in Limgrave."]',
    "6_6":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Quickstep">Quickstep</a>", "Abilità apprezzata dagli astuti e dai veloci. Esegui una manovra di passo rapido che consente di girare attorno ai bersagli agganciati.", "Venduto da Bernahl nella Baracca del Maestro di Guerra a Stormhill, Limgrave."]',
    "6_2":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Bloodhound\'s+Step">Bloodhound\'s Step</a>", "Abilità che permette all\'utente di diventare temporaneamente invisibile mentre schiva ad alta velocità. Si muove più velocemente e copre una distanza maggiore rispetto a un passo rapido normale. Può essere usata per girare attorno ai bersagli agganciati.", "Lasciato cadere dalla Cavalleria Notturna sul ponte a nord di Lenne\'s Rise, in Caelid."]',
    "6_7":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Raptor+of+the+Mists">Raptor of the Mist</a>", "Abbassati in una postura bassa, scomparendo momentaneamente. Se un attacco nemico va a segno, ali d\'uccello permetteranno una rapida fuga in aria.", "Ottenuto durante la missione di Yura, sconfiggendo il suo bersaglio al sito di grazia Main Academy Gate in Liurnia."]',
    "6_1":  '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War:+Beast\'s+Roar">Beast\'s Roar</a>", "Scatena un ruggito bestiale che fende l\'aria come un proiettile in avanzamento.", "Ricompensa da Gurranq dopo 4 radici della morte, al Bestial Sanctum in Caelid."]',
    "20_5": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Piercing+Throw">Piercing Throw</a>", "Lancia l\'arma con una potente rotazione, facendola trapassare i nemici. Con questa abilità, l\'arma può essere lanciata più lontano del normale e perforare i nemici.", "Trovato su uno scarabeo appena a est del sito di grazia Ruined Forge of Starfall Past. Lo troverai sorvegliato da un piccolo gruppo di Semiumani tra una colonna diroccata."]',
    "20_6": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Scattershot+Throw">Scattershot Throw</a>", "Impiega l\'arte della forgiatura per evocare più copie dell\'arma in entrambe le mani e lanciarle tutte insieme. Un input aggiuntivo permette di lanciare di nuovo.", "Si trova uccidendo uno scarabeo. Appena a sud dell\'ingresso della Taylew\'s Ruined Forge, vicino a un ponte. È in alto su un pilastro con alcuni nemici sotto."]',
    "20_9": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Raging+Beast">Raging Beast</a>", "Muoviti con la rapidità di una bestia, salta in alto e colpisci il nemico dall\'alto. Il passo iniziale può essere effettuato in avanti, indietro, a sinistra o a destra. Un attacco forte permette un attacco di follow-up.", "Dal sito di grazia Bridge Leading to the Village seguire il percorso verso nord. Una volta arrivati agli alberi, cercare a est uno Scarabeo Lacrima teletrasportante con la Cenere di Guerra."]',
    "20_10": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Savage+Claws">Savage Claws</a>", "Balza come una bestia per tagliare ferocemente il nemico con gli artigli sinistro e destro.", "Trovato sull\'arma Beast Claw, che cade sconfiggendo Logur, la Bestia Artiglio."]',
    "20_11": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Blind+Spot">Blind Spot</a>", "Balza a distanza ravvicinata per sfruttare il punto cieco del nemico e colpirlo di lato. Gli input determinano da quale lato colpire. Questo attacco scivola sotto la guardia dell\'avversario.", "In dotazione alla Backhand Blade trovata accanto a una bara, nell\'area dei nemici Inquisitori della Gravesite Plain, vicino al primo sito di grazia."]',
    "20_12": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Swift+Slash">Swift Slash</a>", "Abilità tramandata tra i spadaccini degli Incornati. Esegui un rapido passo in avanti per affettare i nemici. Questo colpo tagliente scatena anche un vuoto lacerante. Può essere caricata per aumentare la potenza e la distanza del passo.", "Ricompensa per aver sostenuto l\'Incornato durante il suo combattimento con Leda a Shadowkeep."]',
    "20_13": '        data_it: ["<a href="https://eldenring.wiki.fextralife.com/Ash+of+War+Overhead+Stance">Overhead Stance</a>", "Un\'abilità che inizia con la lama tenuta alta in una postura di attesa. Esegui un attacco normale da questa postura per avanzare e tagliare verso il basso, oppure un attacco forte per una serie di tagli discendenti.", "In dotazione al Grande Katana trovato accanto al Drago Fiamma Fantasma addormentato sul lago, a ovest del sito di grazia Greatbridge, North."]',
}


def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    output_lines = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.rstrip('\n')

        if stripped in TITLE_TRANSLATIONS:
            output_lines.append(line)
            output_lines.append(TITLE_TRANSLATIONS[stripped] + '\n')
            i += 1
            continue

        stripped_s = stripped.strip()
        if stripped_s.startswith('- id:') or stripped_s.startswith('id:'):
            id_val = None
            if '- id:' in stripped_s:
                id_val = stripped_s.split('- id:')[1].strip().strip('"').strip("'")
            elif stripped_s.startswith('id:'):
                id_val = stripped_s.split('id:')[1].strip().strip('"').strip("'")

            if id_val:
                # Strip trailing comment and extra quotes
                id_val = id_val.split('#')[0].strip().strip('"').strip("'")
            if id_val and id_val in DATA_TRANSLATIONS:
                output_lines.append(line)
                i += 1
                while i < len(lines):
                    cur = lines[i]
                    cur_stripped = cur.rstrip('\n').strip()
                    if cur_stripped.startswith('data:'):
                        output_lines.append(cur)
                        it_line = DATA_TRANSLATIONS[id_val]
                        # Escape double quotes in href attributes for valid YAML
                        it_line = re.sub(r'href="([^"]*)"', r'href=\"\1\"', it_line)
                        output_lines.append(it_line + '\n')
                        i += 1
                        break
                    else:
                        output_lines.append(cur)
                        i += 1
                continue
            else:
                output_lines.append(line)
                i += 1
                continue

        output_lines.append(line)
        i += 1

    with open(filepath, 'w', encoding='utf-8') as f:
        f.writelines(output_lines)

    print(f"Done. {len(lines)} input lines -> {len(output_lines)} output lines.")
    print(f"Inserted {len(output_lines) - len(lines)} new lines.")


if __name__ == '__main__':
    process_file('data/checklists/ashesofwar.yaml')
