import yaml
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
DATA_DIR = os.path.join(REPO_ROOT, 'data', 'checklists')

# Official Italian Nomenclature Mapping for Sites of Grace
# Base Game and DLC
mapping = {
    # --- Regions (Base Game) ---
    "Roundtable Hold": "Rocca della Tavola rotonda",
    "Limgrave": "Sepolcride",
    "Stranded Graveyard": "Cimitero abbandonato",
    "Stormhill": "Colle Tempesta",
    "Weeping Peninsula": "Penisola del pianto",
    "Stormveil Castle": "Castello di Grantempesta",
    "Liurnia of the Lakes": "Liurnia lacustre",
    "Bellum Highway": "Strada di Bellum",
    "Ruin-Strewn Precipice": "Precipizio cosparso di rovine",
    "Moonlight Altar": "Altare della Luna",
    "Academy of Raya Lucaria": "Accademia di Raya Lucaria",
    "Altus Plateau": "Altopiano di Altus",
    "Mt. Gelmir": "Monte Gelmir",
    "Capital Outskirts": "Periferia della capitale",
    "Volcano Manor": "Villa Vulcano",
    "Leyndell, Royal Capital": "Leyndell, capitale reale",
    "Subterranean Shunning-Grounds": "Sotterranei dei rinnegati",
    "Leyndell, Ashen Capital": "Leyndell, capitale delle ceneri",
    "Stone Platform": "Piattaforma di pietra",
    "Caelid": "Caelid",
    "Swamp of Aeonia": "Palude di Aeonia",
    "Greyoll's Dragonbarrow": "Tumuli draconici di Greyoll",
    "Forbidden Lands": "Terre proibite",
    "Mountaintops of the Giants": "Vette dei Giganti",
    "Flame Peak": "Picco della Fiamma",
    "Consecrated Snowfield": "Terre sacre",
    "Miquella's Haligtree": "Sacro Albero di Miquella",
    "Elphael, Brace of the Haligtree": "Elphael, sostegno del Sacro Albero",
    "Ainsel River": "Fiume Ainsel",
    "Ainsel River Main": "Corso principale del fiume Ainsel",
    "Lake of Rot": "Lago di Marcescenza",
    "Nokron, Eternal City": "Nokron, la Città Eterna",
    "Siofra River": "Fiume Siofra",
    "Mohgwyn Palace": "Palazzo di Mohgwyn",
    "Deeproot Depths": "Abissi tra le radici",
    "Crumbling Farum Azula": "Farum Azula in frantumi",

    # --- Sites of Grace (Base Game) ---
    "Table of Lost Grace": "Tavolo della grazia perduta",
    "The First Step": "Il primo passo",
    "Church of Elleh": "Chiesa di Elleh",
    "Gatefront": "Davanti al cancello",
    "Waypoint Ruins Cellar": "Sotterranei delle rovine del punto di sosta",
    "Artist's Shack": "Capanna dell'artista",
    "Third Church of Marika": "Terza chiesa di Marika",
    "Fort Haight West": "Forte Haight ovest",
    "Agheel Lake South": "Lago Agheel sud",
    "Agheel Lake North": "Lago Agheel nord",
    "Church of Dragon Communion": "Chiesa della Comunione draconica",
    "Seaside Ruins": "Rovine costiere",
    "Mistwood Outskirts": "Periferia di Tetrobosco",
    "Murkwater Coast": "Costa di Acquaquieta",
    "Summonwater Village Outskirts": "Periferia del villaggio di Idrochiama",
    "Stormfoot Catacombs": "Catacombe di Piè di Tempesta",
    "Murkwater Catacombs": "Catacombe di Acquaquieta",
    "Groveside Cave": "Grotta del bosco",
    "Coastal Cave": "Grotta costiera",
    "Murkwater Cave": "Grotta di Acquaquieta",
    "Highroad Cave": "Grotta della via maestra",
    "Limgrave Tunnels": "Gallerie di Sepolcride",
    "Cave of Knowledge": "Grotta della conoscenza",
    "Stormhill Shack": "Capanna di Colle Tempesta",
    "Castleward Tunnel": "Galleria del castello",
    "Margit, the Fell Omen": "Margit, l'Araldo nefasto",
    "Warmaster's Shack": "Capanna del mastro guerriero",
    "Saintsbridge": "Ponte dei santi",
    "Deathtouched Catacombs": "Catacombe tocca-morte",
    "Limgrave Tower Bridge": "Ponte della torre di Sepolcride",
    "Divine Tower of Limgrave": "Torre divina di Sepolcride",
    "Church of Pilgrimage": "Chiesa del pellegrinaggio",
    "Castle Morne Rampart": "Bastioni di Castel Morne",
    "Tombsward": "Sepolcreto",
    "South of the Lookout Tower": "A sud della vedetta",
    "Ailing Village Outskirts": "Periferia del villaggio malato",
    "Beside The Crater-Pocked Glade": "Presso la radura dei crateri",
    "Isolated Merchant's Shack": "Capanna del mercante isolato",
    "Fourth Church of Marika": "Quarta chiesa di Marika",
    "Bridge of Sacrifice": "Ponte del Sacrificio",
    "Castle Morne Lift": "Ascensore di Castel Morne",
    "Behind The Castle": "Dietro il castello",
    "Beside the Rampart Gaol": "Presso la prigione del bastione",
    "Morne Moangrave": "Sepolcro gemente di Morne",
    "Impaler's Catacombs": "Catacombe dell'Impalatore",
    "Tombsward Catacombs": "Catacombe del Sepolcreto",
    "Earthbore Cave": "Grotta dello scavo",
    "Tombsward Cave": "Grotta del Sepolcreto",
    "Morne Tunnel": "Galleria di Morne",
    "Stormveil Main Gate": "Portone principale di Grantempesta",
    "Gateside Chamber": "Cella presso il cancello",
    "Stormveil Cliffside": "Scogliera di Grantempesta",
    "Rampart Tower": "Torre del bastione",
    "Liftside Chamber": "Cella presso l'ascensore",
    "Secluded Cell": "Cella isolata",
    "Godrick the Grafted": "Godrick l'Innestato",
    "Lake-Facing Cliffs": "Scogliera sul lago",
    "Liurnia Lake Shore": "Riva del lago di Liurnia",
    "Laskyar Ruins": "Rovine di Laskyar",
    "Scenic Isle": "Isola panoramica",
    "Academy Gate Town": "Borgo dei cancelli dell'Accademia",
    "South Raya Lucaria Gate": "Porta sud di Raya Lucaria",
    "Main Academy Gate": "Porta principale dell'Accademia",
    "Liurnia Highway South": "Via maestra di Liurnia sud",
    "Liurnia Highway North": "Via maestra di Liurnia nord",
    "Gate Town Bridge": "Ponte del borgo dei cancelli",
    "Eastern Liurnia Lake Shore": "Riva est del lago di Liurnia",
    "Jarburg": "Jarburg",
    "Ranni's Chamber": "Camera di Ranni",
    "Eastern Tableland": "Altopiano orientale",
    "Church of Vows": "Chiesa dei voti",
    "Ruined Labyrinth": "Labirinto in rovina",
    "Mausoleum Compound": "Complesso del mausoleo",
    "Slumbering Wolf's Shack": "Capanna del lupo dormiente",
    "Boilprawn Shack": "Capanna del gambero bollito",
    "Fallen Ruins of the Lake": "Rovine lacustri abbattute",
    "Folly on the Lake": "Follia sul lago",
    "Village of the Albinaurics": "Villaggio degli Albinauri",
    "Converted Tower": "Torre convertita",
    "Revenger's Shack": "Capanna del vendicatore",
    "Temple Quarter": "Quartiere del tempio",
    "Crystalline Woods": "Boschi cristallini",
    "Foot of the Four Belfries": "Ai piedi dei quattro campanili",
    "The Four Belfries": "I quattro campanili",
    "Sorcerer's Isle": "Isola dello stregone",
    "East Gate Bridge Trestle": "Sostegno del ponte della porta est",
    "Gate Town North": "Borgo dei cancelli nord",
    "Northern Liurnia Lake Shore": "Riva nord del lago di Liurnia",
    "Road to the Manor": "Strada per il maniero",
    "Main Caria Manor Gate": "Portone principale del maniero cariano",
    "Manor Upper Level": "Livello superiore del maniero",
    "Manor Lower Level": "Livello inferiore del maniero",
    "Royal Moongazing Grounds": "Terreni reali di contemplazione lunare",
    "Ranni's Rise": "Guglia di Ranni",
    "Behind Caria Manor": "Dietro il maniero cariano",
    "The Ravine": "Il burrone",
    "Ravine-Veiled Village": "Villaggio velato dal burrone",
    "Cliffbottom Catacombs": "Catacombe di Piè di Scarpata",
    "Road's End Catacombs": "Catacombe della fine della strada",
    "Black Knife Catacombs": "Catacombe dei Neri Coltelli",
    "Stillwater Cave": "Grotta d'Acquastagna",
    "Lakeside Crystal Cave": "Grotta di cristallo sul lago",
    "Academy Crystal Cave": "Grotta di cristallo dell'Accademia",
    "Raya Lucaria Crystal Tunnel": "Galleria cristallina di Raya Lucaria",
    "Study Hall Entrance": "Ingresso della sala studio",
    "Liurnia Tower Bridge": "Ponte della torre di Liurnia",
    "Divine Tower of Liurnia": "Torre divina di Liurnia",
    "East Raya Lucaria Gate": "Porta est di Raya Lucaria",
    "Bellum Church": "Chiesa di Bellum",
    "Grand Lift of Dectus": "Grande montacarichi di Dectus",
    "Frenzied Flame Village Outskirts": "Periferia del villaggio della Fiamma Frenetica",
    "Church of Inhibition": "Chiesa dell'inibizione",
    "Ruin-Strewn Precipice": "Precipizio cosparso di rovine",
    "Ruin-Strewn Precipice Overlook": "Belvedere del precipizio cosparso di rovine",
    "Magma Wyrm Makar": "Makar, drago di magma",
    "Moonlight Altar": "Altare della Luna",
    "Cathedral of Manus Celes": "Cattedrale di Manus Celes",
    "Altar South": "Altare sud",
    "Church of the Cuckoo": "Chiesa del cuculo",
    "Schoolhouse Classroom": "Aula scolastica",
    "Debate Parlor": "Aula del dibattito",
    "Raya Lucaria Grand Library": "Grande biblioteca di Raya Lucaria",
    "Abandoned Coffin": "Bara abbandonata",
    "Erdtree-Gazing Hill": "Colle dell'Albero Madre",
    "Altus Plateau": "Altopiano di Altus",
    "Altus Highway Junction": "Bivio della via maestra dell'Altus",
    "Forest-Spanning Greatbridge": "Granponte della foresta",
    "Bower of Bounty": "Sottobosco dell'abbondanza",
    "Windmill Village": "Villaggio del mulino a vento",
    "Windmill Heights": "Alture del mulino a vento",
    "Road of Iniquity Side Path": "Sentiero della strada dell'iniquità",
    "Rampartside Path": "Sentiero del bastione",
    "Shaded Castle Ramparts": "Bastioni del castello d'Ombra",
    "Shaded Castle Inner Gate": "Porta interna del castello d'Ombra",
    "Castellan's Hall": "Sala del castellano",
    "Unsightly Catacombs": "Catacombe sgradevoli",
    "Sainted Hero's Grave": "Tomba dell'eroe santo",
    "Sage's Cave": "Grotta del saggio",
    "Perfumer's Grotto": "Grotta dei profumieri",
    "Old Altus Tunnel": "Vecchia galleria dell'Altus",
    "Altus Tunnel": "Galleria dell'Altus",
    "Bridge of Iniquity": "Ponte dell'iniquità",
    "First Mt. Gelmir Campsite": "Primo accampamento del monte Gelmir",
    "Ninth Mt. Gelmir Campsite": "Nono accampamento del monte Gelmir",
    "Road of Iniquity": "Strada dell'iniquità",
    "Seethewater River": "Fiume dell'Acqua ribollente",
    "Seethewater Terminus": "Capolinea dell'Acqua ribollente",
    "Craftsman's Shack": "Capanna dell'artigiano",
    "Primeval Sorcerer Azur": "Stregone primordiale Azur",
    "Wyndham Catacombs": "Catacombe di Wyndham",
    "Gelmir Hero's Grave": "Tomba dell'eroe di Gelmir",
    "Seethewater Cave": "Grotta dell'Acqua ribollente",
    "Volcano Cave": "Grotta del vulcano",
    "Outer Wall Phantom Tree": "Albero spettrale delle mura esterne",
    "Minor Erdtree Church": "Chiesa dell'Albero Madre minore",
    "Outer Wall Battleground": "Campo di battaglia delle mura esterne",
    "Hermit Merchant's Shack": "Capanna del mercante eremita",
    "Capital Rampart": "Bastioni della capitale",
    "Auriza Side Tomb": "Tomba laterale di Auriza",
    "Auriza Hero's Grave": "Tomba dell'eroe di Auriza",
    "Sealed Tunnel": "Galleria sigillata",
    "Divine Tower of West Altus: Gate": "Torre divina dell'Altus occidentale: porta",
    "Divine Tower of West Altus": "Torre divina dell'Altus occidentale",
    "Volcano Manor": "Villa Vulcano",
    "Prison Town Church": "Chiesa dell'insediamento carcerario",
    "Temple of Eiglay": "Tempio di Eiglay",
    "Guest Hall": "Salone degli ospiti",
    "Audience Pathway": "Sentiero dell'udienza",
    "Abductor Virgin": "Vergine rapitrice",
    "Subterranean Inquisition Chamber": "Inquisizione sotterranea",
    "Rykard, Lord of Blasphemy": "Rykard, signore della blasfemia",
    "Erdtree Sanctuary": "Santuario dell'Albero Madre",
    "East Capital Rampart": "Bastioni orientali della capitale",
    "Lower Capital Church": "Chiesa della capitale bassa",
    "Avenue Balcony": "Balconata sulla strada",
    "West Capital Rampart": "Bastioni occidentali della capitale",
    "Queen's Bedchamber": "Camera da letto della regina",
    "Fortified Manor, First Floor": "Primo piano del maniero fortificato",
    "Divine Bridge": "Ponte divino",
    "Elden Throne": "Trono ancestrale",
    "Underground Roadside": "Strada sotterranea",
    "Forsaken Depths": "Abissi dei rinnegati",
    "Leyndell Catacombs": "Catacombe di Leyndell",
    "Frenzied Flame Proscription": "Proscrizione della Fiamma Frenetica",
    "Cathedral of the Forsaken": "Cattedrale dei rinnegati",
    "Leyndell, Capital of Ash": "Leyndell, capitale delle ceneri",
    "Fractured Marika": "Marika frantumata",
    "Smoldering Church": "Chiesa ardente",
    "Rotview Balcony": "Balconata sulla putrefazione",
    "Caelem Ruins": "Rovine di Caelem",
    "Fort Gael North": "Forte Gael nord",
    "Smoldering Wall": "Muro ardente",
    "Caelid Highway South": "Via maestra di Caelid sud",
    "Cathedral of Dragon Communion": "Cattedrale della Comunione draconica",
    "Southern Aeonia Swamp Bank": "Riva sud della palude di Aeonia",
    "Sellia Backstreets": "Vicolo di Sellia",
    "Sellia Under-Stair": "Sottoscala di Sellia",
    "Chair-Crypt of Sellia": "Cripta del seggio di Sellia",
    "Church of the Plague": "Chiesa della piaga",
    "Deep Siofra Well": "Pozzo profondo del Siofra",
    "Impassable Greatbridge": "Granponte invalicabile",
    "Chamber Outside the Plaza": "Cella fuori dal piazzale",
    "Redmane Castle Plaza": "Piazzale del castello di Mantorosso",
    "Starscourge Radahn": "Radahn, il Flagello celeste",
    "Minor Erdtree Catacombs": "Catacombe dell'Albero Madre minore",
    "Caelid Catacombs": "Catacombe di Caelid",
    "War-Dead Catacombs": "Catacombe dei caduti in guerra",
    "Abandoned Cave": "Grotta abbandonata",
    "Gaol Cave": "Grotta delle segrete",
    "Gael Tunnel": "Galleria di Gael",
    "Rear Gael Tunnel Entrance": "Ingresso posteriore della galleria di Gael",
    "Sellia Crystal Tunnel": "Galleria cristallina di Sellia",
    "Aeonia Swamp Shore": "Riva della palude di Aeonia",
    "Astray from Caelid Highway North": "Nord della via maestra di Caelid (fuori sentiero)",
    "Heart of Aeonia": "Cuore di Aeonia",
    "Inner Aeonia": "Aeonia interna",
    "Dragonbarrow West": "Tumuli draconici ovest",
    "Fort Faroth": "Forte Faroth",
    "Dragonbarrow Fork": "Bivio dei tumuli draconici",
    "Lenne's Rise": "Guglia di Lenne",
    "Farum Greatbridge": "Granponte di Farum",
    "Bestial Sanctum": "Santuario bestiale",
    "Sellia Hideaway": "Rifugio di Sellia",
    "Dragonbarrow Cave": "Grotta dei tumuli draconici",
    "Divine Tower of Caelid: Center": "Torre divina di Caelid: centro",
    "Divine Tower of Caelid: Basement": "Torre divina di Caelid: seminterrato",
    "Isolated Divine Tower": "Torre divina isolata",
    "Forbidden Lands": "Terre proibite",
    "Grand Lift of Rold": "Grande montacarichi di Rold",
    "Hidden Path to the Haligtree": "Cammino nascosto per il Sacro Albero",
    "Divine Tower of East Altus: Gate": "Torre divina dell'Altus orientale: porta",
    "Divine Tower of East Altus": "Torre divina dell'Altus orientale",
    "Mountaintops of the Giants": "Vette dei Giganti",
    "Zamor Ruins": "Rovine di Zamor",
    "Ancient Snow Valley Ruins": "Rovine dell'antica valle innevata",
    "Freezing Lake": "Lago gelato",
    "First Church of Marika": "Prima chiesa di Marika",
    "Whiteridge Road": "Strada della cresta bianca",
    "Snow Valley Ruins Overlook": "Belvedere delle rovine della valle innevata",
    "Castle Sol Main Gate": "Portone principale di Castel Sol",
    "Church of the Eclipse": "Chiesa dell'eclissi",
    "Castle Sol Rooftop": "Tetto di Castel Sol",
    "Spiritcaller Cave": "Grotta degli evocatori di spiriti",
    "Giants' Gravepost": "Pietra miliare dei giganti",
    "Church of Repose": "Chiesa del riposo",
    "Foot of the Forge": "Ai piedi della forgia",
    "Fire Giant": "Gigante di fuoco",
    "Forge of the Giants": "Forgia dei giganti",
    "Giants' Mountaintop Catacombs": "Catacombe delle Vette dei Giganti",
    "Giant-Conquering Hero's Grave": "Tomba dell'eroe conquistatore di giganti",
    "Consecrated Snowfield": "Terre sacre",
    "Inner Consecrated Snowfield": "Terre sacre interne",
    "Ordina, Liturgical Town": "Ordina, città liturgica",
    "Apostate Derelict": "Ruderi del reietto",
    "Consecrated Snowfield Catacombs": "Catacombe delle Terre sacre",
    "Cave of the Forlorn": "Grotta del reietto",
    "Yelough Anix Tunnel": "Galleria di Yelough Anix",
    "Haligtree Canopy": "Chioma del Sacro Albero",
    "Haligtree Town": "Città del Sacro Albero",
    "Haligtree Town Plaza": "Piazza della città del Sacro Albero",
    "Haligtree Promenade": "Passeggiata del Sacro Albero",
    "Prayer Room": "Stanza della preghiera",
    "Elphael Inner Wall": "Muro interno di Elphael",
    "Drainage Channel": "Canale di drenaggio",
    "Haligtree Roots": "Radici del Sacro Albero",
    "Malenia, Goddess of Rot": "Malenia, dea della marcescenza",
    "Ainsel River Well Depths": "Pozzo del fiume Ainsel (profondità)",
    "Ainsel River Sluice Gate": "Chiusa del fiume Ainsel",
    "Ainsel River Downstream": "Corso inferiore del fiume Ainsel",
    "Dragonkin Soldier of Nokstella": "Soldato draconico di Nokstella",
    "Astel, Naturalborn of the Void": "Astel, progenie del vuoto",
    "Ainsel River Main": "Corso principale del fiume Ainsel",
    "Nokstella, Eternal City": "Nokstella, la Città Eterna",
    "Nokstella Waterfall Basin": "Bacino della cascata di Nokstella",
    "Lake of Rot Shoreside": "Riva del lago di Marcescenza",
    "Grand Cloister": "Gran Chiostro",
    "Nokron, Eternal City": "Nokron, la Città Eterna",
    "Mimic Tear": "Lacrima riflessa",
    "Ancestral Woods": "Boschi ancestrali",
    "Night's Sacred Ground": "Suolo sacro della notte",
    "Aqueduct-Facing Cliffs": "Scogliera sull'acquedotto",
    "Great Waterfall Basin": "Bacino della grande cascata",
    "Siofra River Well Depths": "Pozzo del fiume Siofra (profondità)",
    "Siofra River Bank": "Riva del fiume Siofra",
    "Worshippers' Woods": "Boschi dei seguaci",
    "Below the Well": "Sotto il pozzo",
    "Palace Approach Ledge-Road": "Strada del cornicione del palazzo",
    "Dynasty Mausoleum Entrance": "Ingresso del mausoleo della dinastia",
    "Dynasty Mausoleum Midpoint": "Punto intermedio del mausoleo della dinastia",
    "Cocoon of the Empyrean": "Bozzolo dell'Empireo",
    "Root-Facing Cliffs": "Scogliera sulle radici",
    "Great Waterfall Crest": "Cresta della grande cascata",
    "Deeproot Depths": "Abissi tra le radici",
    "The Nameless Eternal City": "Città Eterna senza nome",
    "Across the Roots": "Attraverso le radici",
    "Prince of Death's Throne": "Trono del Principe della Morte",
    "Crumbling Beast Grave": "Tomba della bestia in frantumi",
    "Crumbling Beast Grave Depths": "Profondità della tomba della bestia",
    "Tempest-Facing Balcony": "Balconata sulla tempesta",
    "Dragon Temple": "Tempio del drago",
    "Dragon Temple Transept": "Transetto del tempio del drago",
    "Dragon Temple Altar": "Altare del tempio del drago",
    "Dragon Temple Lift": "Ascensore del tempio del drago",
    "Dragon Temple Rooftop": "Tetto del tempio del drago",
    "Beside the Great Bridge": "Presso il gran ponte",
    "Dragonlord Placidusax": "Placidusax, signore dei draghi",
    "Maliketh, the Black Blade": "Maliketh, la Lama Nera",

    # --- DLC Sites of Grace (Realm of Shadow / Regno Dell'Ombra) ---
    # Gravesite Plain
    "Gravesite Plain": "Pianura delle Tombe",
    "Scorched Ruins": "Rovine bruciate",
    "Three-Path Cross": "Croce a tre vie",
    "Greatbridge, North": "Granponte nord",
    "Main Gate Cross": "Croce del portone principale",
    "Cliffroad Terminus": "Capolinea della strada della scogliera",
    "Castle Front": "Fronte del castello",
    "Pillar Path Cross": "Croce del sentiero dei pilastri",
    "Pillar Path Waypoint": "Punto di riferimento del sentiero dei pilastri",
    "Ellac River Cave": "Grotta del fiume Ellac",
    "Ellac River Downstream": "Corso inferiore del fiume Ellac",
    "Fog Rift Catacombs": "Catacombe della faglia di nebbia",
    "Belurat Gaol": "Prigione di Belurat",
    "Ruined Forge Lava Intake": "Presa della forgia in rovina di lava",
    "Rivermouth Cave": "Grotta della foce del fiume",
    "Dragon's Pit": "Fossa del drago",
    "Dragon's Pit Terminus": "Capolinea della fossa del drago",
    "Belurat, Tower Settlement": "Belurat, insediamento della torre",
    "Small Private Altar": "Piccolo altare privato",
    "Stagefront": "Fronte del palco",
    "Theatre of the Divine Beast": "Teatro della bestia divina",
    "Castle Ensis Checkpoint": "Checkpoint del castello Ensis",
    "Ensis Moongazing Grounds": "Terreni di contemplazione lunare di Ensis",
    "Castle-Lord's Chamber": "Camera del signore del castello",
    "Abandoned Ailing Village": "Villaggio afflitto abbandonato",

    # Cerulean Coast
    "Cerulean Coast": "Costa Cerulea",
    "Cerulean Coast West": "Costa Cerulea ovest",
    "Cerulean Coast Cross": "Croce della Costa Cerulea",
    "The Fissure": "La fessura",
    "Finger Ruins of Rhia": "Rovine del dito di Rhia",
    "Charo's Hidden Grave": "Tomba nascosta di Charo",
    "Stone Coffin Fissure": "Fessura della bara di pietra",
    "Fissure Cross": "Croce della fessura",
    "Garden of Deep Purple": "Giardino del porpora profondo",
    "Fissure Depths": "Profondità della fessura",
    "Fissure Waypoint": "Punto di riferimento della fessura",
    "Lamenter's Gaol": "Prigione del lamentatore",
    "Grand Altar of Dragon Communion": "Grande altare della Comunione draconica",
    "Foot of the Jagged Peak": "Piede della Cima Frastagliata",
    "Jagged Peak Mountainside": "Fianco della montagna della Cima Frastagliata",
    "Jagged Peak Summit": "Cima del Picco Frastagliato",
    "Rest of the Dread Dragon": "Riposo del drago spaventoso",
    "Jagged Peak": "Picco Frastagliato",

    # Rauh Ruins
    "Ancient Ruins Base": "Base delle rovine antiche",
    "Temple Town Ruins": "Rovine della città tempio",
    "Ravine North": "Burrone nord",
    "Scorpion River Catacombs": "Catacombe del fiume scorpione",
    "Taylew's Ruined Forge": "Forgia in rovina di Taylew",
    "Viaduct Minor Tower": "Torre minore del viadotto",
    "Rauh Ancient Ruins, East": "Antiche rovine di Rauh est",
    "Rauh Ancient Ruins, West": "Antiche rovine di Rauh ovest",
    "Ancient Ruins, Grand Stairway": "Antiche rovine, grande scalinata",
    "Church of the Bud, Main Entrance": "Chiesa del bocciolo, ingresso principale",
    "Church of the Bud": "Chiesa del bocciolo",
    "Rauh Base": "Base di Rauh",

    # Scadu Altus
    "Highroad Cross": "Croce dell'autostrada",
    "Scadu Altus, West": "Scadu Altus ovest",
    "Moorth Ruins": "Rovine di Moorth",
    "Moorth Highway, South": "Autostrada di Moorth sud",
    "Fort of Reprimand": "Forte del rimprovero",
    "Behind the Fort of Reprimand": "Dietro il forte del rimprovero",
    "Scaduview Cross": "Croce di Ombravista",
    "Bonny Village": "Villaggio Bonny",
    "Bridge Leading to the Village": "Ponte che porta al villaggio",
    "Church District Highroad": "Autostrada del distretto della chiesa",
    "Cathedral of Manus Metyr": "Cattedrale di Manus Metyr",
    "Finger Birthing Grounds": "Terreni di nascita delle dita",
    "Castle Watering Hole": "Pozza d'acqua del castello",
    "Recluses' River Upstream": "Corso superiore del fiume dei reclusi",
    "Recluses' River Downstream": "Corso inferiore del fiume dei reclusi",
    "Darklight Catacombs": "Catacombe della luce oscura",
    "Bonny Gaol": "Prigione Bonny",
    "Ruined Forge of Starfall Past": "Forgia in rovina del passato caduto di stelle",
    "Shadow Keep Main Gate": "Portone principale della Rocca delle Ombre",
    "Main Gate Plaza": "Piazzale del portone principale",
    "Sunken Chapel": "Cappella sommersa",
    "Church District Entrance": "Ingresso del distretto della chiesa",
    "Storehouse, First Floor": "Magazzino, primo piano",
    "Storehouse, Fourth Floor": "Magazzino, quarto piano",
    "Storehouse, Seventh Floor": "Magazzino, settimo piano",
    "Storehouse, Back Section": "Magazzino, sezione posteriore",
    "Specimen Storehouse": "Magazzino degli esemplari",
    "Scaduview": "Ombravista",
    "Shadow Keep": "Rocca delle Ombre",
    "Shadow Keep, Church District": "Rocca delle Ombre, distretto della chiesa",

    # Abyssal Woods
    "Abyssal Woods": "Boschi Abissali",
    "Forsaken Graveyard": "Cimitero abbandonato",
    "Woodland Trail": "Sentiero nel bosco",
    "Church Ruins": "Rovine della chiesa",
    "Divided Fall": "Caduta divisa",
    "Manse Hall": "Sala del maniero",
    "Midra's Library": "Biblioteca di Midra",
    "Second Floor Chamber": "Camera del secondo piano",
    "Discussion Chamber": "Camera di discussione",
    "Midra's Manse": "Maniero di Midra",

    # Enir-Ilim
    "Enir-Ilim: Outer Wall": "Enir-Ilim: muro esterno",
    "First Rise": "Prima salita",
    "Spiral Rise": "Salita a spirale",
    "Cleansing Chamber Anteroom": "Anticamera della camera di purificazione",
    "Divine Gate Front Staircase": "Scalinata anteriore del cancello divino",
    "Gate of Divinity": "Cancello della divinità",

    # Others
    "Hinterland Bridge": "Ponte dell'Hinterland",
    "Fingerstone Hill": "Collina della pietra delle dita",
    "Finger Ruins of Dheo": "Rovine del dito di Dheo",
    "Village of Flies": "Villaggio delle mosche",
}

# Regional Groups for DLC
# Realm of Shadow / Regno Dell'Ombra
dlc_graces = [
    # Gravesite Plain
    "Gravesite Plain", "Scorched Ruins", "Three-Path Cross", "Greatbridge, North", "Main Gate Cross", 
    "Cliffroad Terminus", "Castle Front", "Pillar Path Cross", "Pillar Path Waypoint", "Ellac River Cave", 
    "Ellac River Downstream", "Fog Rift Catacombs", "Belurat Gaol", "Ruined Forge Lava Intake", 
    "Rivermouth Cave", "Dragon's Pit", "Dragon's Pit Terminus", "Belurat, Tower Settlement", 
    "Small Private Altar", "Stagefront", "Theatre of the Divine Beast", "Castle Ensis Checkpoint", 
    "Ensis Moongazing Grounds", "Castle-Lord's Chamber", "Abandoned Ailing Village",

    # Cerulean Coast
    "Cerulean Coast", "Cerulean Coast West", "Cerulean Coast Cross", "The Fissure", "Finger Ruins of Rhia", 
    "Charo's Hidden Grave", "Stone Coffin Fissure", "Fissure Cross", "Garden of Deep Purple", 
    "Fissure Depths", "Fissure Waypoint", "Lamenter's Gaol", "Grand Altar of Dragon Communion", 
    "Foot of the Jagged Peak", "Jagged Peak Mountainside", "Jagged Peak Summit", "Rest of the Dread Dragon", 
    "Jagged Peak",

    # Rauh Ruins
    "Ancient Ruins Base", "Temple Town Ruins", "Ravine North", "Scorpion River Catacombs", 
    "Taylew's Ruined Forge", "Viaduct Minor Tower", "Rauh Ancient Ruins, East", "Rauh Ancient Ruins, West", 
    "Ancient Ruins, Grand Stairway", "Church of the Bud, Main Entrance", "Church of the Bud", "Rauh Base",

    # Scadu Altus
    "Highroad Cross", "Scadu Altus, West", "Moorth Ruins", "Moorth Highway, South", "Fort of Reprimand", 
    "Behind the Fort of Reprimand", "Scaduview Cross", "Bonny Village", "Bridge Leading to the Village", 
    "Church District Highroad", "Cathedral of Manus Metyr", "Finger Birthing Grounds", 
    "Castle Watering Hole", "Recluses' River Upstream", "Recluses' River Downstream", "Darklight Catacombs", 
    "Bonny Gaol", "Ruined Forge of Starfall Past", "Shadow Keep Main Gate", "Main Gate Plaza", 
    "Sunken Chapel", "Church District Entrance", "Storehouse, First Floor", "Storehouse, Fourth Floor", 
    "Storehouse, Seventh Floor", "Storehouse, Back Section", "Specimen Storehouse", "Scaduview", 
    "Shadow Keep", "Shadow Keep, Church District",

    # Abyssal Woods
    "Abyssal Woods", "Forsaken Graveyard", "Woodland Trail", "Church Ruins", "Divided Fall", 
    "Manse Hall", "Midra's Library", "Second Floor Chamber", "Discussion Chamber", "Midra's Manse",

    # Enir-Ilim
    "Enir-Ilim: Outer Wall", "First Rise", "Spiral Rise", "Cleansing Chamber Anteroom", 
    "Divine Gate Front Staircase", "Gate of Divinity",

    # Others
    "Hinterland Bridge", "Fingerstone Hill", "Finger Ruins of Dheo", "Village of Flies",
]

def load_yaml(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def save_yaml(data, filepath):
    with open(filepath, 'w', encoding='utf-8') as f:
        yaml.dump(data, f, allow_unicode=True, width=1000, sort_keys=False)

def translate_graces():
    filepath = os.path.join(DATA_DIR, 'graces.yaml')
    data = load_yaml(filepath)
    
    data['title_it'] = "Luoghi di grazia"
    
    # 1. Translate existing base game sections
    for section in data.get('sections', []):
        if 'title' in section:
            section['title_it'] = mapping.get(section['title'], section['title'])
            
        for item in section.get('items', []):
            if isinstance(item, dict) and 'data' in item:
                d = item['data']
                if len(d) > 0:
                    name = d[0]
                    item['data_it'] = [mapping.get(name, name)]

    # 2. Add DLC section "Realm of Shadow"
    dlc_section = {
        "title": "Realm of Shadow",
        "title_it": "Regno Dell'Ombra",
        "items": []
    }
    
    current_id = 1001
    for name in dlc_graces:
        item = {
            "id": str(current_id),
            "data": [name],
            "data_it": [mapping.get(name, name)],
            "dlc": True
        }
        dlc_section["items"].append(item)
        current_id += 1
        
    data['sections'].append(dlc_section)

    save_yaml(data, filepath)
    print(f"Sites of Grace translation applied. Added {len(dlc_graces)} DLC graces.")

if __name__ == '__main__':
    translate_graces()
